# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="mmalhotra2000@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 7002 available to the world outside this container
EXPOSE 7002

# The application's jar file
ARG JAR_FILE=target/ConvertCurrencyMicroserviceApplication.jar

# Add the application's jar to the container
ADD ${JAR_FILE} ConvertCurrencyMicroserviceApplication.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/ConvertCurrencyMicroserviceApplication.jar"]
